// Generated from 02-first-blog-posts.md — do not edit directly
export const entry = {
	slug: '02-first-blog-posts',
	title: 'First Blog Posts',
	navLabel: 'Start Blogging',
	order: 2,
	content:
		'<p>She’s got a blog! And she’s writing! Hooray! </p>\n<p>Now that she’s up and running with her blog, we can start to dive into those gnarly behind the scenes details. The first thing worth noting is that even though she’s using the Leaflet UI to create these blog posts, they aren’t being saved to a server that Leaflet is running. So where are they being saved?  Well… to a server Bluesky is running.</p>\n<p>“They’re being saved to a server that Bluesky is running?” you cry, “that’s a little confusing.”</p>\n<p>And I agree; it seems a little contradictory to what we’re advocating: the at proto is all about owning your own data.</p>\n<p>As we continue to peel away the layers of this onion, suffice it to say that while Bluesky does actually run the server, the data being saved, as well as the control and ownership of that data remains with her. We will dive deeper into this technology set up known as a personal data server in a future entry on this journey.  If you’d like to dive into that now, take a look at our PDS topical entry.</p>\n<p>Back to the main thread: she writes a post, it gets saved to her PDS, and you can view it on leaflet. So what? </p>\n<p>While any blogging platform worth having allows you and others to view posts, they generally don’t like (or even allow) you to look at the data outside of their platform. Forcing you through their platform is what allows them control for revenue and user retention purposes. This is also where the at proto starts to look a little different than traditional applications.</p>\n<p>Without getting into custom viewers and other complex solutions, there are a couple publicly available tools that make it easy to look at your at proto data. \nPDSls (add link to view her data here) \nDirect link (show the data raw in the browser)</p>\n<p>In an attempt to keep this particular entry from growing quite long we’re gonna wrap it up here with another time for reflection and thoughts from our representative Mom.  </p>\n<judy thoughts><p>I can tell you’re at the edge of your seat so come on back for the next entry where we talk about things like interoperability and standard data structures. Ooooohhh!</p>\n',
};
