// Generated from single-identity.md — do not edit directly
export const entry = {
	slug: 'single-identity',
	title: 'Single Identity',
	short: "You're just always you... everywhere.",
	order: 1,
	content:
		'<p>&quot;A person is a person no matter how small&quot; -- Dr. Seuss</p>\n<hr>\n<p>This quote certainly reminds me of childhood but I have a much more direct connection to this quote from my first (and best) boss.  We built custom systems for our clients and often if a particular user worked for more than one &quot;brand&quot; of our clients we created two separate user records for them.  For instance, &quot;Susie @ Old Navy&quot; and &quot;Susie @ Banana Republic&quot; because those are two brands within the Gap, Inc parent company.  But, as it turns out, Susie is an actual human and trying to explain to Susie that we had her as two people made her very confused. </p>\n<p>So that great boss just kept repeating Dr. Seuss at us until we figured out a way to make it work in the application code. Susie did end up with just one account. However, if you look across the internet at Susie&#39;s identity today, she&#39;s undoubtedly created dozens or perhaps hundreds of accounts (aka identities).  Even after we merged our two instances of Susie back into just the single one, she still has plenty to keep track of. But what if she didn&#39;t?</p>\n<p>Part of the goal with AT Proto is the idea of one identity that carries across multiple applications. Rather than &quot;creating an account&quot; in each application she uses throughout her day, what if she could just say &quot;Hey I&#39;m Susie&quot; and all of those apps were able to verify she was, in fact, Susie?  And then just... moved on?  That is, to me, one of the cornerstones to the shift in the internet that the AT Protocol is trying to get us to see.  And in many ways it&#39;s what the web always intended, but more on that in another post. </p>\n<p>Think of the idea of this &quot;single identity&quot; as like the &quot;Sign in with Google/Facebook/Apple&quot; but on steroids.  You still are logging in but all of those are using their system of identifying you to allow you into another site.  If you&#39;re trying to get into your local knitting store&#39;s site and you use &quot;Sign In with Apple&quot; the knitting store is trusting Apple&#39;s ability to verify your identity and then letting you in.  </p>\n<p>But what if you could just “sign in as you”? The AT Protocol aims to give humans a way to identify themselves on the internet outside of a giant corporate overlord.  </p>\n<p>Seem too good to be true?  It isn&#39;t. It is here and being used by millions of people every day.</p>\n',
};
